export interface RalColor {
  code: string
  name: string
  hex:  string
  group: string
}

export const RAL_COLORS: RalColor[] = [
  // ── Yellow ──────────────────────────────────────────────────────
  { code: 'RAL 1000', name: 'Green beige',          hex: '#CDBA88', group: 'Yellow' },
  { code: 'RAL 1001', name: 'Beige',                hex: '#D0B084', group: 'Yellow' },
  { code: 'RAL 1002', name: 'Sand yellow',          hex: '#D2AA6D', group: 'Yellow' },
  { code: 'RAL 1003', name: 'Signal yellow',        hex: '#F9A000', group: 'Yellow' },
  { code: 'RAL 1004', name: 'Golden yellow',        hex: '#E49300', group: 'Yellow' },
  { code: 'RAL 1005', name: 'Honey yellow',         hex: '#CB7B12', group: 'Yellow' },
  { code: 'RAL 1006', name: 'Maize yellow',         hex: '#E3861A', group: 'Yellow' },
  { code: 'RAL 1007', name: 'Daffodil yellow',      hex: '#E8850C', group: 'Yellow' },
  { code: 'RAL 1011', name: 'Brown beige',          hex: '#AF8A54', group: 'Yellow' },
  { code: 'RAL 1012', name: 'Lemon yellow',         hex: '#D9C022', group: 'Yellow' },
  { code: 'RAL 1013', name: 'Oyster white',         hex: '#E9E0CC', group: 'Yellow' },
  { code: 'RAL 1014', name: 'Ivory',                hex: '#DFCEA1', group: 'Yellow' },
  { code: 'RAL 1015', name: 'Light ivory',          hex: '#EAD9A3', group: 'Yellow' },
  { code: 'RAL 1016', name: 'Sulfur yellow',        hex: '#EDF060', group: 'Yellow' },
  { code: 'RAL 1017', name: 'Saffron yellow',       hex: '#F4A53B', group: 'Yellow' },
  { code: 'RAL 1018', name: 'Zinc yellow',          hex: '#F3E03B', group: 'Yellow' },
  { code: 'RAL 1019', name: 'Grey beige',           hex: '#9E9067', group: 'Yellow' },
  { code: 'RAL 1020', name: 'Olive yellow',         hex: '#8E8947', group: 'Yellow' },
  { code: 'RAL 1021', name: 'Rape yellow',          hex: '#EFA622', group: 'Yellow' },
  { code: 'RAL 1023', name: 'Traffic yellow',       hex: '#F7B500', group: 'Yellow' },
  { code: 'RAL 1024', name: 'Ochre yellow',         hex: '#BA8B26', group: 'Yellow' },
  { code: 'RAL 1026', name: 'Luminous yellow',      hex: '#FFFF00', group: 'Yellow' },
  { code: 'RAL 1027', name: 'Curry',                hex: '#A97E26', group: 'Yellow' },
  { code: 'RAL 1028', name: 'Melon yellow',         hex: '#F4A400', group: 'Yellow' },
  { code: 'RAL 1032', name: 'Broom yellow',         hex: '#DBA544', group: 'Yellow' },
  { code: 'RAL 1033', name: 'Dahlia yellow',        hex: '#F18A00', group: 'Yellow' },
  { code: 'RAL 1034', name: 'Pastel yellow',        hex: '#EBA951', group: 'Yellow' },
  { code: 'RAL 1035', name: 'Pearl beige',          hex: '#9B9172', group: 'Yellow' },
  { code: 'RAL 1036', name: 'Pearl gold',           hex: '#8D7135', group: 'Yellow' },
  { code: 'RAL 1037', name: 'Sun yellow',           hex: '#F09600', group: 'Yellow' },

  // ── Orange ──────────────────────────────────────────────────────
  { code: 'RAL 2000', name: 'Yellow orange',        hex: '#DA6E00', group: 'Orange' },
  { code: 'RAL 2001', name: 'Red orange',           hex: '#BE4F1B', group: 'Orange' },
  { code: 'RAL 2002', name: 'Vermilion',            hex: '#C63927', group: 'Orange' },
  { code: 'RAL 2003', name: 'Pastel orange',        hex: '#F57130', group: 'Orange' },
  { code: 'RAL 2004', name: 'Pure orange',          hex: '#E05D00', group: 'Orange' },
  { code: 'RAL 2005', name: 'Luminous orange',      hex: '#FF4B00', group: 'Orange' },
  { code: 'RAL 2007', name: 'Luminous bright orange', hex: '#FFAF00', group: 'Orange' },
  { code: 'RAL 2008', name: 'Bright red orange',    hex: '#EB6A35', group: 'Orange' },
  { code: 'RAL 2009', name: 'Traffic orange',       hex: '#DA4900', group: 'Orange' },
  { code: 'RAL 2010', name: 'Signal orange',        hex: '#D05B28', group: 'Orange' },
  { code: 'RAL 2011', name: 'Deep orange',          hex: '#EC7C25', group: 'Orange' },
  { code: 'RAL 2012', name: 'Salmon orange',        hex: '#D4624B', group: 'Orange' },
  { code: 'RAL 2013', name: 'Pearl orange',         hex: '#923E25', group: 'Orange' },

  // ── Red ─────────────────────────────────────────────────────────
  { code: 'RAL 3000', name: 'Flame red',            hex: '#A81C07', group: 'Red' },
  { code: 'RAL 3001', name: 'Signal red',           hex: '#A01B1B', group: 'Red' },
  { code: 'RAL 3002', name: 'Carmine red',          hex: '#9B1C1C', group: 'Red' },
  { code: 'RAL 3003', name: 'Ruby red',             hex: '#8D1B1B', group: 'Red' },
  { code: 'RAL 3004', name: 'Purple red',           hex: '#6D2323', group: 'Red' },
  { code: 'RAL 3005', name: 'Wine red',             hex: '#5B1B1B', group: 'Red' },
  { code: 'RAL 3007', name: 'Black red',            hex: '#2E1717', group: 'Red' },
  { code: 'RAL 3009', name: 'Oxide red',            hex: '#6B2424', group: 'Red' },
  { code: 'RAL 3011', name: 'Brown red',            hex: '#772626', group: 'Red' },
  { code: 'RAL 3012', name: 'Beige red',            hex: '#C9896E', group: 'Red' },
  { code: 'RAL 3013', name: 'Tomato red',           hex: '#952727', group: 'Red' },
  { code: 'RAL 3014', name: 'Antique pink',         hex: '#C97777', group: 'Red' },
  { code: 'RAL 3015', name: 'Light pink',           hex: '#D8A5A5', group: 'Red' },
  { code: 'RAL 3016', name: 'Coral red',            hex: '#AC4040', group: 'Red' },
  { code: 'RAL 3017', name: 'Rose',                 hex: '#CB5B5B', group: 'Red' },
  { code: 'RAL 3018', name: 'Strawberry red',       hex: '#BE2626', group: 'Red' },
  { code: 'RAL 3020', name: 'Traffic red',          hex: '#BB2020', group: 'Red' },
  { code: 'RAL 3022', name: 'Salmon pink',          hex: '#CF7058', group: 'Red' },
  { code: 'RAL 3024', name: 'Luminous red',         hex: '#FF0000', group: 'Red' },
  { code: 'RAL 3026', name: 'Luminous bright red',  hex: '#FF1A1A', group: 'Red' },
  { code: 'RAL 3027', name: 'Raspberry red',        hex: '#961A1A', group: 'Red' },
  { code: 'RAL 3028', name: 'Pure red',             hex: '#CB2121', group: 'Red' },
  { code: 'RAL 3031', name: 'Orient red',           hex: '#A13232', group: 'Red' },
  { code: 'RAL 3032', name: 'Pearl ruby red',       hex: '#711919', group: 'Red' },
  { code: 'RAL 3033', name: 'Pearl pink',           hex: '#B44D4D', group: 'Red' },

  // ── Violet ──────────────────────────────────────────────────────
  { code: 'RAL 4001', name: 'Red lilac',            hex: '#8B5A75', group: 'Violet' },
  { code: 'RAL 4002', name: 'Red violet',           hex: '#7B3B57', group: 'Violet' },
  { code: 'RAL 4003', name: 'Heather violet',       hex: '#C47A8C', group: 'Violet' },
  { code: 'RAL 4004', name: 'Claret violet',        hex: '#5C2238', group: 'Violet' },
  { code: 'RAL 4005', name: 'Blue lilac',           hex: '#7A6B8C', group: 'Violet' },
  { code: 'RAL 4006', name: 'Traffic purple',       hex: '#8C2060', group: 'Violet' },
  { code: 'RAL 4007', name: 'Purple violet',        hex: '#3D1F3D', group: 'Violet' },
  { code: 'RAL 4008', name: 'Signal violet',        hex: '#7A3070', group: 'Violet' },
  { code: 'RAL 4009', name: 'Pastel violet',        hex: '#9C7A8C', group: 'Violet' },
  { code: 'RAL 4010', name: 'Telemagenta',          hex: '#C0397A', group: 'Violet' },
  { code: 'RAL 4011', name: 'Pearl violet',         hex: '#6B4E6B', group: 'Violet' },
  { code: 'RAL 4012', name: 'Pearl blackberry',     hex: '#4D3D5C', group: 'Violet' },

  // ── Blue ────────────────────────────────────────────────────────
  { code: 'RAL 5000', name: 'Violet blue',          hex: '#233A5C', group: 'Blue' },
  { code: 'RAL 5001', name: 'Green blue',           hex: '#1B3E5C', group: 'Blue' },
  { code: 'RAL 5002', name: 'Ultramarine blue',     hex: '#122E5C', group: 'Blue' },
  { code: 'RAL 5003', name: 'Sapphire blue',        hex: '#1A2E4A', group: 'Blue' },
  { code: 'RAL 5004', name: 'Black blue',           hex: '#0D1B2A', group: 'Blue' },
  { code: 'RAL 5005', name: 'Signal blue',          hex: '#154889', group: 'Blue' },
  { code: 'RAL 5007', name: 'Brilliant blue',       hex: '#2B6090', group: 'Blue' },
  { code: 'RAL 5008', name: 'Grey blue',            hex: '#2B4057', group: 'Blue' },
  { code: 'RAL 5009', name: 'Azure blue',           hex: '#25567B', group: 'Blue' },
  { code: 'RAL 5010', name: 'Gentian blue',         hex: '#0E4C8A', group: 'Blue' },
  { code: 'RAL 5011', name: 'Steel blue',           hex: '#152542', group: 'Blue' },
  { code: 'RAL 5012', name: 'Light blue',           hex: '#3882B8', group: 'Blue' },
  { code: 'RAL 5013', name: 'Cobalt blue',          hex: '#0E2A52', group: 'Blue' },
  { code: 'RAL 5014', name: 'Pigeon blue',          hex: '#6A8BA8', group: 'Blue' },
  { code: 'RAL 5015', name: 'Sky blue',             hex: '#2570B0', group: 'Blue' },
  { code: 'RAL 5017', name: 'Traffic blue',         hex: '#045F9C', group: 'Blue' },
  { code: 'RAL 5018', name: 'Turquoise blue',       hex: '#2E8080', group: 'Blue' },
  { code: 'RAL 5019', name: 'Capri blue',           hex: '#0E4F80', group: 'Blue' },
  { code: 'RAL 5020', name: 'Ocean blue',           hex: '#0A3040', group: 'Blue' },
  { code: 'RAL 5021', name: 'Water blue',           hex: '#108080', group: 'Blue' },
  { code: 'RAL 5022', name: 'Night blue',           hex: '#0E1E57', group: 'Blue' },
  { code: 'RAL 5023', name: 'Distant blue',         hex: '#3A6082', group: 'Blue' },
  { code: 'RAL 5024', name: 'Pastel blue',          hex: '#5B8CA8', group: 'Blue' },
  { code: 'RAL 5025', name: 'Pearl gentian blue',   hex: '#1A4C72', group: 'Blue' },
  { code: 'RAL 5026', name: 'Pearl night blue',     hex: '#0D1E3D', group: 'Blue' },

  // ── Green ───────────────────────────────────────────────────────
  { code: 'RAL 6000', name: 'Patina green',         hex: '#3A6B4A', group: 'Green' },
  { code: 'RAL 6001', name: 'Emerald green',        hex: '#28612A', group: 'Green' },
  { code: 'RAL 6002', name: 'Leaf green',           hex: '#2E6428', group: 'Green' },
  { code: 'RAL 6003', name: 'Olive green',          hex: '#4A5330', group: 'Green' },
  { code: 'RAL 6004', name: 'Blue green',           hex: '#1A3A36', group: 'Green' },
  { code: 'RAL 6005', name: 'Moss green',           hex: '#1E4222', group: 'Green' },
  { code: 'RAL 6006', name: 'Grey olive',           hex: '#3B3D2A', group: 'Green' },
  { code: 'RAL 6007', name: 'Bottle green',         hex: '#2B3A22', group: 'Green' },
  { code: 'RAL 6008', name: 'Brown green',          hex: '#333327', group: 'Green' },
  { code: 'RAL 6009', name: 'Fir green',            hex: '#1F3329', group: 'Green' },
  { code: 'RAL 6010', name: 'Grass green',          hex: '#3A6B28', group: 'Green' },
  { code: 'RAL 6011', name: 'Reseda green',         hex: '#5E7846', group: 'Green' },
  { code: 'RAL 6012', name: 'Black green',          hex: '#2B3B33', group: 'Green' },
  { code: 'RAL 6013', name: 'Reed green',           hex: '#7A7844', group: 'Green' },
  { code: 'RAL 6014', name: 'Yellow olive',         hex: '#474434', group: 'Green' },
  { code: 'RAL 6015', name: 'Black olive',          hex: '#3B3B2B', group: 'Green' },
  { code: 'RAL 6016', name: 'Turquoise green',      hex: '#1A6B3E', group: 'Green' },
  { code: 'RAL 6017', name: 'May green',            hex: '#4E8030', group: 'Green' },
  { code: 'RAL 6018', name: 'Yellow green',         hex: '#62A432', group: 'Green' },
  { code: 'RAL 6019', name: 'Pastel green',         hex: '#C2D8B0', group: 'Green' },
  { code: 'RAL 6020', name: 'Chrome green',         hex: '#2A4022', group: 'Green' },
  { code: 'RAL 6021', name: 'Pale green',           hex: '#7FA870', group: 'Green' },
  { code: 'RAL 6022', name: 'Olive drab green',     hex: '#3C3C22', group: 'Green' },
  { code: 'RAL 6024', name: 'Traffic green',        hex: '#2A8850', group: 'Green' },
  { code: 'RAL 6025', name: 'Fern green',           hex: '#486030', group: 'Green' },
  { code: 'RAL 6026', name: 'Opal green',           hex: '#1E6040', group: 'Green' },
  { code: 'RAL 6027', name: 'Light green',          hex: '#7ABCB0', group: 'Green' },
  { code: 'RAL 6028', name: 'Pine green',           hex: '#2C5040', group: 'Green' },
  { code: 'RAL 6029', name: 'Mint green',           hex: '#187840', group: 'Green' },
  { code: 'RAL 6032', name: 'Signal green',         hex: '#28804A', group: 'Green' },
  { code: 'RAL 6033', name: 'Mint turquoise',       hex: '#3E8872', group: 'Green' },
  { code: 'RAL 6034', name: 'Pastel turquoise',     hex: '#7AB8B0', group: 'Green' },
  { code: 'RAL 6035', name: 'Pearl green',          hex: '#1E5822', group: 'Green' },
  { code: 'RAL 6036', name: 'Pearl opal green',     hex: '#1A5C48', group: 'Green' },
  { code: 'RAL 6037', name: 'Pure green',           hex: '#0E8040', group: 'Green' },
  { code: 'RAL 6038', name: 'Luminous green',       hex: '#00F000', group: 'Green' },

  // ── Grey ────────────────────────────────────────────────────────
  { code: 'RAL 7000', name: 'Squirrel grey',        hex: '#7B8E8E', group: 'Grey' },
  { code: 'RAL 7001', name: 'Silver grey',          hex: '#8C9EA8', group: 'Grey' },
  { code: 'RAL 7002', name: 'Olive grey',           hex: '#7E7E5E', group: 'Grey' },
  { code: 'RAL 7003', name: 'Moss grey',            hex: '#6C6C54', group: 'Grey' },
  { code: 'RAL 7004', name: 'Signal grey',          hex: '#9A9A9A', group: 'Grey' },
  { code: 'RAL 7005', name: 'Mouse grey',           hex: '#696966', group: 'Grey' },
  { code: 'RAL 7006', name: 'Beige grey',           hex: '#6C6454', group: 'Grey' },
  { code: 'RAL 7008', name: 'Khaki grey',           hex: '#6E6040', group: 'Grey' },
  { code: 'RAL 7009', name: 'Green grey',           hex: '#4E5448', group: 'Grey' },
  { code: 'RAL 7010', name: 'Tarpaulin grey',       hex: '#484848', group: 'Grey' },
  { code: 'RAL 7011', name: 'Iron grey',            hex: '#4C5462', group: 'Grey' },
  { code: 'RAL 7012', name: 'Basalt grey',          hex: '#4E5A5A', group: 'Grey' },
  { code: 'RAL 7013', name: 'Brown grey',           hex: '#4C4A3C', group: 'Grey' },
  { code: 'RAL 7015', name: 'Slate grey',           hex: '#40454E', group: 'Grey' },
  { code: 'RAL 7016', name: 'Anthracite grey',      hex: '#293137', group: 'Grey' },
  { code: 'RAL 7017', name: 'Chocolate grey',       hex: '#3D3535', group: 'Grey' },
  { code: 'RAL 7018', name: 'Grey',                 hex: '#4A4B4E', group: 'Grey' },
  { code: 'RAL 7019', name: 'Grey',                 hex: '#3C3D40', group: 'Grey' },
  { code: 'RAL 7020', name: 'Grey',                 hex: '#656563', group: 'Grey' },
  { code: 'RAL 7021', name: 'Black grey',           hex: '#232B2B', group: 'Grey' },
  { code: 'RAL 7022', name: 'Umbra grey',           hex: '#3C3C36', group: 'Grey' },
  { code: 'RAL 7023', name: 'Concrete grey',        hex: '#7A7872', group: 'Grey' },
  { code: 'RAL 7024', name: 'Graphite grey',        hex: '#3E454E', group: 'Grey' },
  { code: 'RAL 7025', name: 'Pearl grey',           hex: '#8C8880', group: 'Grey' },
  { code: 'RAL 7026', name: 'Granite grey',         hex: '#2D3640', group: 'Grey' },
  { code: 'RAL 7027', name: 'Warm grey',            hex: '#7C7C72', group: 'Grey' },
  { code: 'RAL 7028', name: 'Deep grey',            hex: '#3C3C3A', group: 'Grey' },
  { code: 'RAL 7029', name: 'Pebble grey',          hex: '#7A7870', group: 'Grey' },
  { code: 'RAL 7030', name: 'Stone grey',           hex: '#8E8878', group: 'Grey' },
  { code: 'RAL 7031', name: 'Blue grey',            hex: '#4E6070', group: 'Grey' },
  { code: 'RAL 7032', name: 'Pebble grey',          hex: '#B8B0A0', group: 'Grey' },
  { code: 'RAL 7033', name: 'Cement grey',          hex: '#7A7E6C', group: 'Grey' },
  { code: 'RAL 7034', name: 'Yellow grey',          hex: '#8A826A', group: 'Grey' },
  { code: 'RAL 7035', name: 'Light grey',           hex: '#C8C8C8', group: 'Grey' },
  { code: 'RAL 7036', name: 'Platinum grey',        hex: '#8A8880', group: 'Grey' },
  { code: 'RAL 7037', name: 'Dusty grey',           hex: '#7A7A78', group: 'Grey' },
  { code: 'RAL 7038', name: 'Agate grey',           hex: '#B0AEA8', group: 'Grey' },
  { code: 'RAL 7039', name: 'Quartz grey',          hex: '#6A6662', group: 'Grey' },
  { code: 'RAL 7040', name: 'Window grey',          hex: '#9EA8A8', group: 'Grey' },
  { code: 'RAL 7041', name: 'Traffic grey A',       hex: '#86878A', group: 'Grey' },
  { code: 'RAL 7042', name: 'Traffic grey B',       hex: '#8E9090', group: 'Grey' },
  { code: 'RAL 7043', name: 'Traffic grey C',       hex: '#4A4A4A', group: 'Grey' },
  { code: 'RAL 7044', name: 'Silk grey',            hex: '#BABABC', group: 'Grey' },
  { code: 'RAL 7045', name: 'Telegrey 1',           hex: '#8A9092', group: 'Grey' },
  { code: 'RAL 7046', name: 'Telegrey 2',           hex: '#787E82', group: 'Grey' },
  { code: 'RAL 7047', name: 'Telegrey 4',           hex: '#C8C8C6', group: 'Grey' },
  { code: 'RAL 7048', name: 'Pearl mouse grey',     hex: '#6A6260', group: 'Grey' },

  // ── Brown ───────────────────────────────────────────────────────
  { code: 'RAL 8000', name: 'Green brown',          hex: '#74603A', group: 'Brown' },
  { code: 'RAL 8001', name: 'Ochre brown',          hex: '#8E5B2A', group: 'Brown' },
  { code: 'RAL 8002', name: 'Signal brown',         hex: '#6B3A2A', group: 'Brown' },
  { code: 'RAL 8003', name: 'Clay brown',           hex: '#7A4422', group: 'Brown' },
  { code: 'RAL 8004', name: 'Copper brown',         hex: '#7E3E22', group: 'Brown' },
  { code: 'RAL 8007', name: 'Fawn brown',           hex: '#6B4226', group: 'Brown' },
  { code: 'RAL 8008', name: 'Olive brown',          hex: '#614C2A', group: 'Brown' },
  { code: 'RAL 8011', name: 'Nut brown',            hex: '#4E301C', group: 'Brown' },
  { code: 'RAL 8012', name: 'Red brown',            hex: '#5C2A1A', group: 'Brown' },
  { code: 'RAL 8014', name: 'Sepia brown',          hex: '#3A2214', group: 'Brown' },
  { code: 'RAL 8015', name: 'Chestnut brown',       hex: '#5A2418', group: 'Brown' },
  { code: 'RAL 8016', name: 'Mahogany brown',       hex: '#4A2016', group: 'Brown' },
  { code: 'RAL 8017', name: 'Chocolate brown',      hex: '#3A1E14', group: 'Brown' },
  { code: 'RAL 8019', name: 'Grey brown',           hex: '#362E2A', group: 'Brown' },
  { code: 'RAL 8022', name: 'Black brown',          hex: '#1A1210', group: 'Brown' },
  { code: 'RAL 8023', name: 'Orange brown',         hex: '#7A4020', group: 'Brown' },
  { code: 'RAL 8024', name: 'Beige brown',          hex: '#7E5034', group: 'Brown' },
  { code: 'RAL 8025', name: 'Pale brown',           hex: '#7A5A42', group: 'Brown' },
  { code: 'RAL 8028', name: 'Terra brown',          hex: '#4E3220', group: 'Brown' },
  { code: 'RAL 8029', name: 'Pearl copper',         hex: '#7A4028', group: 'Brown' },

  // ── White / Black ────────────────────────────────────────────────
  { code: 'RAL 9001', name: 'Cream',                hex: '#F4F0E0', group: 'White/Black' },
  { code: 'RAL 9002', name: 'Grey white',           hex: '#E4E4DC', group: 'White/Black' },
  { code: 'RAL 9003', name: 'Signal white',         hex: '#F4F4F4', group: 'White/Black' },
  { code: 'RAL 9004', name: 'Signal black',         hex: '#2A2A2A', group: 'White/Black' },
  { code: 'RAL 9005', name: 'Jet black',            hex: '#0E0E10', group: 'White/Black' },
  { code: 'RAL 9006', name: 'White aluminium',      hex: '#A8A8A8', group: 'White/Black' },
  { code: 'RAL 9007', name: 'Grey aluminium',       hex: '#8A8880', group: 'White/Black' },
  { code: 'RAL 9010', name: 'Pure white',           hex: '#F8F8F8', group: 'White/Black' },
  { code: 'RAL 9011', name: 'Graphite black',       hex: '#1C2028', group: 'White/Black' },
  { code: 'RAL 9012', name: 'Clean room white',     hex: '#F0EEEC', group: 'White/Black' },
  { code: 'RAL 9016', name: 'Traffic white',        hex: '#F6F6F6', group: 'White/Black' },
  { code: 'RAL 9017', name: 'Traffic black',        hex: '#1E1E1E', group: 'White/Black' },
  { code: 'RAL 9018', name: 'Papyrus white',        hex: '#D4D4C8', group: 'White/Black' },
  { code: 'RAL 9022', name: 'Pearl light grey',     hex: '#909090', group: 'White/Black' },
  { code: 'RAL 9023', name: 'Pearl dark grey',      hex: '#7A7A7A', group: 'White/Black' },
]

export const RAL_GROUPS = [
  'Yellow', 'Orange', 'Red', 'Violet', 'Blue', 'Green', 'Grey', 'Brown', 'White/Black',
] as const
